import os
os.system('cmd /c "curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py"')
os.system('cmd /c "python get-pip.py"')
os.system('cmd /c "pip install joblib"')
os.system('cmd /c "pip install scipy"')
os.system('cmd /c "pip install numpy"')
os.system('cmd /c "pip install pillow"')
os.system('cmd /c "pip install matplotlib"')
os.system('cmd /c "pip install keras"')
os.system('cmd /c "pip install tensorflow"')